### ISSUE TITLE
希望增加对外部图片数据的支持

### ISSUE THREAD

**Issue by geekroscom** [HorizonRDK/hobot_image_publisher#10]
增加对外部图片数据的支持，可以将X3PI作为一个推理服务，用户可以在外部任意设备调用话题发布base64之类的原始图片数据进行推理，如果没有这个的支持，那么用户需要将图片先存到X3PI，这里会造成一定的损耗。希望采纳。

**Comment by zhukao** [comment]
> 增加对外部图片数据的支持，可以将X3PI作为一个推理服务，用户可以在外部任意设备调用话题发布base64之类的原始图片数据进行推理，如果没有这个的支持，那么用户需要将图片先存到X3PI，这里会造成一定的损耗。希望采纳。

具体是什么功能或者可以具体说明下这个需求的使用方法吗。
目前图片发布工具只支持发布本地图片或者视频，工具的输入数据源是本地的路径或者文件，针对提到的需求，工具的输入数据源应该是什么呢？

**Comment by geekroscom** [comment]
是我之前有提到过的仿真中相机画面数据，这个仿真是运行在客户机上的一个上位机，比如仿真里搭建了一个测试的场景，场景模拟了一些特定的3D场景，比如火灾现场、救援现场等，作用是将仿真相机看到的画面（仿真会处理为base64格式）发送到X3PI的Node话题上进行推理。

我知道目前图片发布工具只支持发布本地图片或者视频，像一些jpg、png之类的图片是可以转为base64发送的，可以省去将base64存到X3PI本地的环节，减少传输上的损耗。

**Comment by geekroscom** [comment]
base64数据我会通过客户机连接rosbridge发送到具体的ROS话题上

**Comment by zhukao** [comment]
> base64数据我会通过客户机连接rosbridge发送到具体的ROS话题上

base64数据会通过什么类型的消息发布？

**Comment by geekroscom** [comment]
> > base64数据我会通过客户机连接rosbridge发送到具体的ROS话题上
> 
> base64数据会通过什么类型的消息发布？

是一个图片的base64的字符串

**Comment by zhukao** [comment]
> > > base64数据我会通过客户机连接rosbridge发送到具体的ROS话题上
> > 
> > 
> > base64数据会通过什么类型的消息发布？
> 
> 是一个图片的base64的字符串
是ros2的话题消息吗？

**Comment by geekroscom** [comment]
> > > > base64数据我会通过客户机连接rosbridge发送到具体的ROS话题上
> > > 
> > > 
> > > base64数据会通过什么类型的消息发布？
> > 
> > 
> > 是一个图片的base64的字符串
> > 是ros2的话题消息吗？

是的，会将图片的base64以字符串的形式发送给ros话题，你那边可能需要把base64转为实际需要的图片。

**Comment by geekroscom** [comment]
类似：
```
if (image_format == "base64") {
    // 从base64字符串解码得到图片
    cv::Mat img = base64_decode(image_source);

    // 后续处理与其他图片格式一致

  } else {
     // 其他图片格式处理
  }
```

**Comment by zhukao** [comment]
> > > > > base64数据我会通过客户机连接rosbridge发送到具体的ROS话题上
> > > > 
> > > > 
> > > > base64数据会通过什么类型的消息发布？
> > > 
> > > 
> > > 是一个图片的base64的字符串
> > > 是ros2的话题消息吗？
> 
> 是的，会将图片的base64以字符串的形式发送给ros话题，你那边可能需要把base64转为实际需要的图片。

对应于ros2的哪个消息？
在客户机端将base64数据解码成jpeg后，使用ros2的sensor_msgs::msg::Image类型消息直接发布是不是最优方法？

**Comment by zhukao** [comment]
> 类似：
> 
> ```
> if (image_format == "base64") {
>     // 从base64字符串解码得到图片
>     cv::Mat img = base64_decode(image_source);
> 
>     // 后续处理与其他图片格式一致
> 
>   } else {
>      // 其他图片格式处理
>   }
> ```

根据需求描述，看起来不是工具新支持一种图片编码格式就能够满足的了，属于是另一种工具了。当前工具是基于ros2的图片发布工具进行扩展，只支持发布本地图片功能。

**Comment by geekros** [comment]
好吧。

**Comment by geekros** [comment]
我自己写吧

**Comment by geekroscom** [comment]
我自己来弄吧

**Comment by geekroscom** [comment]
我自己来弄吧
